/**
 * Maan Customer API for backend
 * define ok 代表已定義好，incomplete 代表尚未實作。 如果都沒有標注，代表該 api 已可使用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.InsertReturn
import io.swagger.client.model.JourneyCopyRequest
import io.swagger.client.model.JourneyDefaultItemsRequest
import io.swagger.client.model.JourneyInsertRequest
import io.swagger.client.model.JourneyRequest
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object JourneyApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (successful operation)
   * 
   * @param token 
   * @param jid 
   * @param body 
   */
  def journeysDefaultListGet(token: String, jid: Int, body: Option[JourneyDefaultItemsRequest] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://virtserver.swaggerhub.com/goodspeed666/maan_customer/1.0.0", "/journeys/default_list", "application/json")
      .withBody(body)
      .withPathParam("jid", jid)
      .withHeaderParam("token", token)
      .withSuccessResponse[Unit](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 201 : InsertReturn (successful operation)
   *   code 400 :  (Customized error message)
   * 
   * @param token 
   * @param jid 
   * @param body 
   */
  def journeysJidCopyPost(token: String, jid: Int, body: Option[JourneyCopyRequest] = None): ApiRequest[InsertReturn] =
    ApiRequest[InsertReturn](ApiMethods.POST, "https://virtserver.swaggerhub.com/goodspeed666/maan_customer/1.0.0", "/journeys/{jid}/copy", "application/json")
      .withBody(body)
      .withPathParam("jid", jid)
      .withHeaderParam("token", token)
      .withSuccessResponse[InsertReturn](201)
      .withErrorResponse[Unit](400)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (successful operation)
   *   code 400 :  (Customized error message)
   * 
   * @param token 
   * @param jid 
   */
  def journeysJidDelete(token: String, jid: Int): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://virtserver.swaggerhub.com/goodspeed666/maan_customer/1.0.0", "/journeys/{jid}", "application/json")
      .withPathParam("jid", jid)
      .withHeaderParam("token", token)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (successful operation)
   *   code 400 :  (Customized error message)
   * 
   * @param token 
   * @param jid 
   * @param body 
   */
  def journeysJidGet(token: String, jid: Int, body: Option[JourneyRequest] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://virtserver.swaggerhub.com/goodspeed666/maan_customer/1.0.0", "/journeys/{jid}", "application/json")
      .withBody(body)
      .withPathParam("jid", jid)
      .withHeaderParam("token", token)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (successful operation)
   *   code 400 :  (Customized error message)
   * 
   * @param token 
   * @param jid 
   * @param body 
   */
  def journeysJidPost(token: String, jid: Int, body: Option[JourneyInsertRequest] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/goodspeed666/maan_customer/1.0.0", "/journeys/{jid}", "application/json")
      .withBody(body)
      .withPathParam("jid", jid)
      .withHeaderParam("token", token)
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](400)
        /**
   * 
   * 
   * Expected answers:
   *   code 201 : InsertReturn (successful operation)
   *   code 400 :  (Customized error message)
   * 
   * @param token 
   * @param page 
   * @param body 
   */
  def journeysPost(token: String, page: Option[Int] = None, body: Option[JourneyInsertRequest] = None): ApiRequest[InsertReturn] =
    ApiRequest[InsertReturn](ApiMethods.POST, "https://virtserver.swaggerhub.com/goodspeed666/maan_customer/1.0.0", "/journeys", "application/json")
      .withBody(body)
      .withQueryParam("page", page)
      .withHeaderParam("token", token)
      .withSuccessResponse[InsertReturn](201)
      .withErrorResponse[Unit](400)
      

}

