/**
 * Maan Customer API for backend
 * define ok 代表已定義好，incomplete 代表尚未實作。 如果都沒有標注，代表該 api 已可使用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.InsertReturn
import io.swagger.client.model.NotificationList
import io.swagger.client.model.NotificationRequest
import io.swagger.client.model.NotificationUpdateRequest
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object NotificationApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 200 : NotificationList (successful operation)
   * 
   * @param token 
   */
  def notificationsGet(token: String): ApiRequest[NotificationList] =
    ApiRequest[NotificationList](ApiMethods.GET, "https://virtserver.swaggerhub.com/goodspeed666/maan_customer/1.0.0", "/notifications", "application/json")
      .withHeaderParam("token", token)
      .withSuccessResponse[NotificationList](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (successful operation)
   * 
   * @param token 
   * @param id 
   */
  def notificationsIdDelete(token: String, id: Int): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://virtserver.swaggerhub.com/goodspeed666/maan_customer/1.0.0", "/notifications/{id}", "application/json")
      .withPathParam("id", id)
      .withHeaderParam("token", token)
      .withSuccessResponse[Unit](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 : NotificationList (successful operation)
   * 
   * @param token 
   */
  def notificationsIdGet(token: String): ApiRequest[NotificationList] =
    ApiRequest[NotificationList](ApiMethods.GET, "https://virtserver.swaggerhub.com/goodspeed666/maan_customer/1.0.0", "/notifications/{id}", "application/json")
      .withHeaderParam("token", token)
      .withSuccessResponse[NotificationList](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (successful operation)
   * 
   * @param token 
   * @param id 
   * @param body 
   */
  def notificationsIdPost(token: String, id: Int, body: Option[NotificationUpdateRequest] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/goodspeed666/maan_customer/1.0.0", "/notifications/{id}", "application/json")
      .withBody(body)
      .withPathParam("id", id)
      .withHeaderParam("token", token)
      .withSuccessResponse[Unit](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 201 : InsertReturn (successful operation)
   * 
   * @param token 
   * @param body 
   */
  def notificationsPost(token: String, body: Option[NotificationRequest] = None): ApiRequest[InsertReturn] =
    ApiRequest[InsertReturn](ApiMethods.POST, "https://virtserver.swaggerhub.com/goodspeed666/maan_customer/1.0.0", "/notifications", "application/json")
      .withBody(body)
      .withHeaderParam("token", token)
      .withSuccessResponse[InsertReturn](201)
      

}

