/**
 * Maan Customer API for backend
 * define ok 代表已定義好，incomplete 代表尚未實作。 如果都沒有標注，代表該 api 已可使用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CompletedSurveyListInner (
  sid: Option[Int] = None,
  tid: Option[Int] = None,
  `type`: Option[Int] = None,
  title: Option[String] = None,
  cid: Option[String] = None,
  customerName: Option[Int] = None,
  room: Option[String] = None,
  status: Option[String] = None,
  /* 活動時間 */
  startTime: Option[String] = None,
  /* 填寫時間 */
  createdAt: Option[String] = None
) extends ApiModel


