/**
 * Maan Customer API for backend
 * define ok 代表已定義好，incomplete 代表尚未實作。 如果都沒有標注，代表該 api 已可使用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CourseListInner (
  id: Option[Int] = None,
  formId: Option[CourseListInnerFormId] = None,
  courseName: Option[CourseListInnerCourseName] = None,
  classTime: Option[String] = None,
  quota: Option[Int] = None,
  /* 已報名 */
  applied: Option[Int] = None,
  /* 已點名 */
  attended: Option[Int] = None
) extends ApiModel


