/**
 * Maan Customer API for backend
 * define ok 代表已定義好，incomplete 代表尚未實作。 如果都沒有標注，代表該 api 已可使用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CourseDataRequest (
  formId: String,
  courseName: Int,
  description: Option[String] = None,
  /* Y-m-d H:i */
  classTime: String,
  duration: String,
  quota: Int,
  /* Y-m-d H:i */
  startTime: String,
  /* Y-m-d H:i */
  endTime: String,
  teacher: Option[String] = None,
  location: String,
  isExtra: Option[Boolean] = None,
  condition1: Option[String] = None,
  condition2: Option[Int] = None,
  status: Boolean
) extends ApiModel


