/**
 * Maan Customer API for backend
 * define ok 代表已定義好，incomplete 代表尚未實作。 如果都沒有標注，代表該 api 已可使用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CourseActivityRequest (
  courseId: Option[Int] = None,
  formId: Option[String] = None,
  /* Y-m-d H:i */
  startTime: Option[String] = None,
  /* Y-m-d H:i */
  endTime: Option[String] = None,
  appliedPeople: Option[Seq[CourseActivityRequestAppliedPeople]] = None,
  /* 預定時間結束 */
  onTime: Option[Boolean] = None
) extends ApiModel


