/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CourseActivityPhotoRequest (
  photo1: Option[String],
  photo2: Option[String],
  photo3: Option[String],
  photo4: Option[String],
  photo5: Option[String],
  photo6: Option[String],
  photo7: Option[String],
  photo8: Option[String],
  photo9: Option[String],
  photo10: Option[String]
) extends ApiModel


