/**
 * Maan Customer API for backend
 * define ok 代表已定義好，incomplete 代表尚未實作。 如果都沒有標注，代表該 api 已可使用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CourseActivityPhotoRequest (
  photo1: Option[String] = None,
  photo2: Option[String] = None,
  photo3: Option[String] = None,
  photo4: Option[String] = None,
  photo5: Option[String] = None,
  photo6: Option[String] = None,
  photo7: Option[String] = None,
  photo8: Option[String] = None,
  photo9: Option[String] = None,
  photo10: Option[String] = None
) extends ApiModel


