/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CourseDataRequest (
  formId: String,
  courseName: Int,
  description: Option[String],
  /* yyyy-mm-dd H:i */
  classTime: String,
  duration: String,
  quota: Int,
  /* yyyy-mm-dd H:i */
  startTime: String,
  /* yyyy-mm-dd H:i */
  endTime: String,
  teacher: Option[String],
  location: String,
  isExtra: Option[Boolean],
  condition1: Option[String],
  condition2: Option[Int],
  status: Boolean
) extends ApiModel


