/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class GetSurvey (
  sid: Option[Int],
  `type`: Option[Int],
  title: Option[String],
  startTime: Option[String],
  during: Option[Int],
  target: Option[Int],
  targetList: Option[Seq[GetSurveyTargetList]],
  targetDueStart: Option[String],
  targetDueEnd: Option[String],
  notify: Option[Boolean],
  status: Option[Boolean],
  header: Option[String],
  footer: Option[String],
  createdAt: Option[String],
  questions: Option[Seq[GetSurveyQuestions]]
) extends ApiModel


