/**
 * Maan Customer API for backend
 * define ok 代表已定義好，incomplete 代表尚未實作。 如果都沒有標注，代表該 api 已可使用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class GetSurveyReportQuestions (
  name: Option[String] = None,
  kind: Option[String] = None,
  options: Option[Seq[GetSurveyReportOptions]] = None,
  comment: Option[String] = None,
  count: Option[Int] = None,
  avg: Option[Float] = None,
  weight: Option[Int] = None
) extends ApiModel


