/**
 * Maan Customer API for backend
 * define ok 代表已定義好，incomplete 代表尚未實作。 如果都沒有標注，代表該 api 已可使用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class GetSurveyReport (
  sid: Option[Int] = None,
  title: Option[String] = None,
  teacher: Option[String] = None,
  location: Option[String] = None,
  startTime: Option[String] = None,
  classTime: Option[String] = None,
  onTime: Option[String] = None,
  quota: Option[Int] = None,
  questions: Option[Seq[GetSurveyReportQuestions]] = None,
  photos: Option[Seq[CourseActivityResponsePhotos]] = None,
  adminComment: Option[Seq[GetSurveyReportAdminComment]] = None
) extends ApiModel


