/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class GetSurveyReport (
  sid: Option[Int],
  title: Option[String],
  teacher: Option[String],
  location: Option[String],
  startTime: Option[String],
  classTime: Option[String],
  onTime: Option[String],
  quota: Option[Int],
  questions: Option[Seq[GetSurveyReportQuestions]],
  photos: Option[Seq[CourseActivityResponsePhotos]],
  adminComment: Option[Seq[GetSurveyReportAdminComment]]
) extends ApiModel


