/**
 * Maan Customer API for backend
 * define ok 代表已定義好，incomplete 代表尚未實作。 如果都沒有標注，代表該 api 已可使用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class NotificationListInner (
  id: Option[Int] = None,
  `type`: Option[Int] = None,
  message: Option[String] = None,
  landing: Option[Any] = None,
  target: Option[Int] = None,
  targetDueStart: Option[String] = None,
  targetDueEnd: Option[String] = None,
  targetList: Option[Seq[NotificationListInnerTargetList]] = None,
  sendTime: Option[String] = None,
  createdUser: Option[String] = None,
  status: Option[Int] = None,
  progrss: Option[String] = None
) extends ApiModel


