/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class NotificationListInner (
  id: Option[Int],
  `type`: Option[Int],
  message: Option[String],
  landing: Option[Any],
  target: Option[Int],
  targetDueStart: Option[String],
  targetDueEnd: Option[String],
  targetList: Option[Seq[NotificationListInnerTargetList]],
  sendTime: Option[String],
  createdUser: Option[String],
  status: Option[Int],
  progrss: Option[String]
) extends ApiModel


