/**
 * Maan Customer API for backend
 * define ok 代表已定義好，incomplete 代表尚未實作。 如果都沒有標注，代表該 api 已可使用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class SurveyResponse (
  `type`: String,
  title: String,
  startTime: String,
  during: Int,
  target: Int,
  targetList: Option[Seq[CourseActivityRequestAppliedPeople]] = None,
  targetDueStart: Option[String] = None,
  targetDueEnd: Option[String] = None,
  notify: Option[Boolean] = None,
  status: Option[Boolean] = None,
  header: Option[String] = None,
  footer: Option[String] = None,
  questions: Seq[SurveyResponseQuestions]
) extends ApiModel


