/**
 * Maan Customer API for backend
 * define ok 代表已定義好，incomplete 代表尚未實作。 如果都沒有標注，代表該 api 已可使用。
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class UserListInner (
  id: Option[Int] = None,
  account: Option[String] = None,
  name: Option[String] = None,
  email: Option[String] = None,
  dept: Option[String] = None,
  role: Option[String] = None,
  organization: Option[String] = None,
  branch: Option[String] = None,
  status: Option[Boolean] = None,
  employeeId: Option[String] = None,
  picture: Option[String] = None,
  lastLoginAt: Option[String] = None,
  createdAt: Option[String] = None,
  updatedAt: Option[String] = None
) extends ApiModel


